import "../../styles/expenses.css";

import jsPDF from "jspdf";

export default function TripSummary({
  prediction,
  selectedWisata,
  totalBudget,
  tripDate,
  onDelete,
}) {
  if (!prediction) return null;

  // =====================================================
  // EXPORT PDF
  // =====================================================

  const handleExportPDF = () => {
    const doc = new jsPDF();

    // ===================================================
    // TITLE
    // ===================================================

    doc.setFontSize(22);

    doc.text("SMART BUDGET TRAVEL ITINERARY", 20, 25);

    // ===================================================
    // ROUTE
    // ===================================================

    doc.setFontSize(14);

    doc.text(
      `Route : ${prediction.from_city} → ${prediction.destination}`,
      20,
      45,
    );

    doc.text(`Trip Date : ${tripDate}`, 20, 55);

    doc.text(`Duration : ${prediction.days} Days`, 20, 65);

    doc.text(`Travelers : ${prediction.travelers} Person`, 20, 75);

    doc.text(`Budget Type : ${prediction.budget_type}`, 20, 85);

    // ===================================================
    // AI DESTINATION
    // ===================================================

    if (selectedWisata) {
      doc.setFontSize(16);

      doc.text("AI Recommended Destination", 20, 105);

      doc.setFontSize(13);

      doc.text(`Destination : ${selectedWisata.activity_name}`, 20, 118);

      doc.text(
        `Ticket Price : Rp ${selectedWisata.activity_price?.toLocaleString(
          "id-ID",
        )}`,
        20,
        128,
      );

      doc.text(`Rating : ${selectedWisata.rating}`, 20, 138);
    }

    // ===================================================
    // BUDGET BREAKDOWN
    // ===================================================

    const transport = prediction.predicted_budget * 0.45;

    const hotel = prediction.predicted_budget * 0.25;

    const food = prediction.predicted_budget * 0.2;

    const activity =
      prediction.predicted_budget * 0.1 + (selectedWisata?.activity_price || 0);

    doc.setFontSize(16);

    doc.text("Budget Breakdown", 20, 160);

    doc.setFontSize(13);

    doc.text(`Transport : Rp ${transport.toLocaleString("id-ID")}`, 20, 173);

    doc.text(`Hotel : Rp ${hotel.toLocaleString("id-ID")}`, 20, 183);

    doc.text(`Food : Rp ${food.toLocaleString("id-ID")}`, 20, 193);

    doc.text(`Activity : Rp ${activity.toLocaleString("id-ID")}`, 20, 203);

    // ===================================================
    // TOTAL
    // ===================================================

    doc.setFontSize(18);

    doc.text(
      `TOTAL BUDGET : Rp ${Number(totalBudget).toLocaleString("id-ID")}`,
      20,
      225,
    );

    // ===================================================
    // FOOTER
    // ===================================================

    doc.setFontSize(11);

    doc.text("Generated by Smart Budget App AI Travel Planner", 20, 270);

    // ===================================================
    // SAVE PDF
    // ===================================================

    doc.save(`Trip-${prediction.destination}.pdf`);
  };

  return (
    <div className="card trip-card">
      {/* =========================================== */}
      {/* HEADER */}
      {/* =========================================== */}

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "start",
          gap: "12px",
          flexWrap: "wrap",
        }}
      >
        {/* LEFT */}

        <div>
          <h2>
            {prediction.from_city}
            {" → "}
            {prediction.destination}
          </h2>

          <p>🗓 {tripDate}</p>
        </div>

        {/* RIGHT */}

        <div
          style={{
            display: "flex",
            gap: "10px",
          }}
        >
          <button className="export-btn" onClick={handleExportPDF}>
            Export PDF
          </button>

          <button className="delete-btn" onClick={onDelete}>
            Hapus
          </button>
        </div>
      </div>

      <br />

      {/* =========================================== */}
      {/* TOTAL */}
      {/* =========================================== */}

      <h3>Rp {prediction.predicted_budget?.toLocaleString("id-ID")}</h3>

      <br />

      {/* =========================================== */}
      {/* INFO */}
      {/* =========================================== */}

      <div className="trip-info-grid">
        <div className="trip-info-item">
          <span>🗓 Duration</span>

          <h4>{prediction.days} Days</h4>
        </div>

        <div className="trip-info-item">
          <span>👥 Travelers</span>

          <h4>{prediction.travelers} Person</h4>
        </div>

        <div className="trip-info-item">
          <span> Budget</span>

          <h4>{prediction.budget_type}</h4>
        </div>
      </div>

      <br />

      {/* =========================================== */}
      {/* DESTINATION */}
      {/* =========================================== */}

      {selectedWisata && (
        <div>
          <h3>AI Selected Destination</h3>

          <p>{selectedWisata.activity_name}</p>

          <p>
            Ticket : Rp {selectedWisata.activity_price?.toLocaleString("id-ID")}
          </p>

          <p>⭐ {selectedWisata.rating}</p>
        </div>
      )}
    </div>
  );
}
